# ===============================================
# Profil de Developpement (dev)
# ===============================================

# Affichage detaille et formatage des requetes SQL
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Niveaux de logs en developpement
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.tn.esprit.autoloc=DEBUG
